version: '3.8'

services:
  db:
    networks:
     - pg-network
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    networks:
     - pg-network
    build:
      context: .
    depends_on:
      - db
    container_name: python_app_it2

volumes:
  db_data:
networks:
  pg-network:
